### Checking the performance of CSV v/s parquet formats

In [36]:
import pandas as pd
from pathlib import Path

DATA_PATH_CSV = Path("../data/processed/index/master/nifty50_index_master_2016_2026.csv")

df = pd.read_csv(DATA_PATH_CSV)

df.sort_values("trade_date")

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02

In [37]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/processed/index/parquet/nifty50_index_master_2016_2026.parquet")
df = pd.read_parquet(DATA_PATH)

df.sort_values("trade_date")

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02

<b>Note:</b><i>From above example we can't see the difference between csv & parquet. But, <b>Parquet is more faster than csv</b> (we can see the clear difference in data of larger files. for ex. equity master dataset (having rows 4.2+ M))</i>

### <b>Note:</b> All the above data is sorted in accending order by trade_date as we will work on the features that are heavily dependes on Dates

### We need to sort the dates

In [38]:
df=df.sort_values("trade_date")

In [39]:
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02

## Daily Return

In [40]:
df["return_1d"] = df["closing_index_value"].pct_change()
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429

pct_change() calculates the percentage change between the current value and the previous value.</br>
Return=(Current Price−Previous Price​)/Previous Price</br>
If the Result is 0.05 then the returns are 0.05*100 = 5% High from last closing

## Weekly Momentum

In [41]:
df["return_5d"] = df["closing_index_value"].pct_change(5)
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952

## Monthly Momentum

In [42]:
df["return_20d"] = df["closing_index_value"].pct_change(20)
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691,0.003232
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046,0.002502
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658,0.006947
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353,0.014227
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952,-0.008877

## Rolling Volatility

In [43]:
df["volatility_20d"] = df["return_1d"].rolling(20).std()
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN,NaN
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN,NaN
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN,NaN
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691,0.003232,0.010048
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046,0.002502,0.010038
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658,0.006947,0.009993
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353,0.014227,0.009354
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952,-0.008877,0.009494

moving window of 20 rows (20 days)</br>
looks at the previous 20 days of returns_1d</br>
std() calculates the standard deviation of the values inside the window</br>
In simple words, How much the market has been fluctuating over the last 20 days</br>
Higher std → more volatile market</br>
Lower std → stable market</br>
| Volatility (`volatility_20d`) | Approx %    | Market Type | Meaning                          |
| ----------------------------- | ----------- | ----------- | -------------------------------- |
| **< 0.007**                   | < 0.7%      | Low         | Stable / trending market         |
| **0.007 – 0.015**             | 0.7% – 1.5% | Medium      | Normal market movement           |
| **> 0.015**                   | > 1.5%      | High        | Panic / crash / highly uncertain |

## Drawdown

In [44]:
rolling_max = df["closing_index_value"].cummax()
df["drawdown"] = df["closing_index_value"] / rolling_max - 1
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN,NaN,-0.021587
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN,NaN,-0.022422
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN,NaN,-0.027903
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN,NaN,-0.049591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2511,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691,0.003232,0.010048,-0.034332
2512,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046,0.002502,0.010038,-0.032134
2513,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658,0.006947,0.009993,-0.031601
2515,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353,0.014227,0.009354,-0.043675
2481,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952,-0.008877,0.009494,-0.055561

cummax() means cumulative maximum</br>
(highest value the index has reached so far)</br>
Drawdown = (Current Price​)/(Peak Price) - 1</br>
how far the price has fallen from its highest point</br>
If drawdown is -0.028 then -2.8% drawdown (Meaning price is 2.8% below its peak)

## Volume Momentum

In [45]:
df["volume_change"] = df["volume"].pct_change(5)
df.head(6)

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown,volume_change
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000,NaN
25,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN,NaN,-0.021587,NaN
34,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN,NaN,-0.022422,NaN
42,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN,NaN,-0.027903,NaN
49,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN,NaN,-0.049591,NaN
57,NIFTY 50,7611.65,7634.10,7581.05,7601.35,33.05,0.44,162348690,6753.57,20.56,3.05,1.52,2016-01-08,0.004367,-0.04544,NaN,NaN,-0.045440,1.503687

## Market Breadth Features (From Equity Dataset)

Market breadth measures how many stocks are moving up or down in the market.
It helps identify market regimes such as broad rallies or weak participation.

We compute:
- Percentage of stocks with positive daily return

## Load the Equity Dataset

In [46]:
# Equity dataset path
equity_path = Path("../data/processed/equity/parquet/nse_master_2016_2026.parquet")

equity = pd.read_parquet(equity_path)

equity.head()

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
0,20MICRONS,EQ,27.95,29.15,27.50,28.50,28.50,28.15,32780,928645.65,209,INE144J01027,2016-04-01
1,3IINFOTECH,EQ,4.20,4.55,4.10,4.40,4.45,4.15,1719404,7552327.65,779,INE748C01020,2016-04-01
2,3MINDIA,EQ,10655.05,10880.00,10655.05,10826.05,10870.00,10724.95,100,1080720.35,49,INE470A01017,2016-04-01
3,8KMILES,EQ,1998.25,2029.00,1951.00,2014.25,2025.00,1998.25,22146,44328051.80,2381,INE650K01013,2016-04-01
4,A2ZINFRA,EQ,19.85,21.20,19.85,20.85,20.75,19.90,193654,4030127.55,915,INE619I01012,2016-04-01

## Compute Daily Returns for Each Stock

In [47]:
# sort values by symbol and trade_date
equity = equity.sort_values(["symbol", "trade_date"])

# daily return per stock
equity["return_1d"] = equity.groupby("symbol")["close"].pct_change()

equity.head()

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d
5972,20MICRONS,EQ,36.00,36.3,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN
41898,20MICRONS,EQ,35.55,37.5,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886
56863,20MICRONS,EQ,36.45,36.7,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749
65880,20MICRONS,EQ,35.95,36.5,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626
76398,20MICRONS,EQ,35.90,35.9,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154

We calculate daily returns for each stock using percentage change.
This allows us to determine whether each stock moved up or down on a given day.

## Compute Breadth Signal

In [ ]:
breadth = equity.groupby("trade_date")["return_1d"].apply(
    lambda x: (x > 0).sum() / len(x)
)

breadth = breadth.rename("breadth_positive").reset_index()

breadth.head()

  trade_date  breadth_positive
0 2016-01-01          0.000000
1 2016-01-04          0.298913
2 2016-01-05          0.675932
3 2016-01-06          0.366848
4 2016-01-07          0.086043

Breadth Positive = Number of stocks with positive return / Total stocks

Values close to:
1.0 → Broad market rally  
0.5 → Mixed market  
0.0 → Broad market decline

## Merge Breadth with Index Dataset

In [49]:
df = df.merge(breadth, on="trade_date", how="left")

df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown,volume_change,breadth_positive
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000
1,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN,NaN,-0.021587,NaN,0.298913
2,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN,NaN,-0.022422,NaN,0.675932
3,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN,NaN,-0.027903,NaN,0.366848
4,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN,NaN,-0.049591,NaN,0.086043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691,0.003232,0.010048,-0.034332,0.160217,0.264377
2515,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046,0.002502,0.010038,-0.032134,0.033453,0.525620
2516,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658,0.006947,0.009993,-0.031601,0.214472,0.536394
2517,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353,0.014227,0.009354,-0.043675,0.418751,0.297476
2518,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952,-0.008877,0.009494,-0.055561,0.300882,0.125464

## Save Features (Partitioned Parquet)

In [50]:
df["year"] = df["trade_date"].dt.year
df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,...,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown,volume_change,breadth_positive,year
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,...,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000,2016
1,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,...,1.48,2016-01-04,-0.021587,NaN,NaN,NaN,-0.021587,NaN,0.298913,2016
2,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,...,1.49,2016-01-05,-0.000854,NaN,NaN,NaN,-0.022422,NaN,0.675932,2016
3,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,...,1.49,2016-01-06,-0.005607,NaN,NaN,NaN,-0.027903,NaN,0.366848,2016
4,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,...,1.53,2016-01-07,-0.022310,NaN,NaN,NaN,-0.049591,NaN,0.086043,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,...,1.23,2026-02-24,-0.011214,-0.011691,0.003232,0.010048,-0.034332,0.160217,0.264377,2026
2515,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,...,1.22,2026-02-25,0.002275,-0.013046,0.002502,0.010038,-0.032134,0.033453,0.525620,2026
2516,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,...,1.22,2026-02-26,0.000551,0.001658,0.006947,0.009993,-0.031601,0.214472,0.536394,2026
2517,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,...,1.24,2026-02-27,-0.012468,-0.015353,0.014227,0.009354,-0.043675,0.418751,0.297476,2026
2518,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,...,1.25,2026-03-02,-0.012429,-0.032952,-0.008877,0.009494,-0.055561,0.300882,0.125464,2026

In [51]:
import sys

# Add project root directory to sys.path
sys.path.append(str(Path().resolve().parents[0]))

# importing get_logger function from scripts.logger
from scripts.logger import get_logger

logger = get_logger(__name__)

output_path = Path("../data/features/index")

# Create index if not exists
if not output_path.exists():
    output_path.mkdir(parents=True, exist_ok=True)
    logger.info(f"Created directory: {output_path}")
else:
    logger.info(f"Directory already exisits:{output_path}")

years = df["year"].unique()

for year in years:
    try:
    
        df_year = df[df["year"] == year]
        
        file_path = output_path / f"index_features_{year}.parquet"

        # Check if parquet already exists
        if file_path.exists():
            logger.info(f"File already exists for year {year}: {file_path}")
        else:
            df_year.to_parquet(file_path, index=False)
            logger.info(f"Parquet file created for year {year}: {file_path}")
    
    except Exception as e:
        logger.error(f"Error while creating parquet for year {year}: {e}")