### Checking the performance of CSV v/s parquet formats

In [25]:
import pandas as pd
from pathlib import Path

DATA_PATH_CSV = Path("../data/processed/equity/master/nse_master_2016_2026.csv")
df = pd.read_csv(DATA_PATH_CSV)
df = df.sort_values(["symbol","trade_date"])
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16

In [26]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path("../data/processed/equity/parquet/nse_master_2016_2026.parquet")
df = pd.read_parquet(DATA_PATH)
df = df.sort_values(["symbol","trade_date"])
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16

<b>Note:</b><i>From above example we can see the difference between csv & parquet. That, <b>Parquet is more faster than csv</b></i>

### For Feature Engineering we have grouped the stocks by dates 
<p>For example, TCS</p>

In [27]:
df[df["symbol"]=="TCS"]

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date
7273,TCS,EQ,2439.00,2439.00,2412.25,2416.40,2414.10,2436.85,356131,8.631649e+08,15545,INE467B01029,2016-01-01
43204,TCS,EQ,2410.15,2414.00,2366.05,2369.60,2373.00,2416.40,935092,2.227161e+09,72341,INE467B01029,2016-01-04
58171,TCS,EQ,2385.00,2386.60,2341.00,2348.95,2349.85,2369.60,1339010,3.151409e+09,97799,INE467B01029,2016-01-05
67184,TCS,EQ,2350.20,2386.15,2350.20,2381.60,2382.00,2348.95,1326614,3.149627e+09,43208,INE467B01029,2016-01-06
77706,TCS,EQ,2370.00,2382.90,2360.00,2371.25,2379.00,2381.60,1599790,3.787837e+09,29836,INE467B01029,2016-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4219871,TCS,EQ,2641.00,2647.50,2561.30,2573.70,2581.00,2676.30,7798833,2.017552e+10,424406,INE467B01029,2026-02-24
4222290,TCS,EQ,2596.00,2654.20,2595.00,2629.30,2629.00,2573.70,3621285,9.531785e+09,170312,INE467B01029,2026-02-25
4224709,TCS,EQ,2650.00,2671.00,2635.00,2647.70,2649.00,2629.30,3464267,9.178108e+09,148371,INE467B01029,2026-02-26
4227126,TCS,EQ,2681.60,2688.60,2626.10,2637.40,2639.70,2647.70,5083717,1.344593e+10,166737,INE467B01029,2026-02-27
4229549,TCS,EQ,2592.00,2623.80,2580.30,2613.50,2611.70,2637.40,3374385,8.794898e+09,227265,INE467B01029,2026-03-02

## Daily Return

In [28]:
df["return_1d"] = df.groupby("symbol")["close"].pct_change()
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000

## Short Momentum

In [29]:
df["return_5d"] = df.groupby("symbol")["close"].pct_change(5)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333

## Medium Momentum

In [30]:
df["return_20d"] = df.groupby("symbol")["close"].pct_change(20)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000

## Rolling Volatility

In [31]:
df["volatility_20d"] = (
    df.groupby("symbol")["return_1d"]
      .rolling(20)
      .std()
      .reset_index(level=0, drop=True)
)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081

## Liquidity Features

### Traded Value

In [32]:
df["traded_value"] = df["close"] * df["tottrdqty"]
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN,2587833.60
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN,9286217.10
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN,2633366.25
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN,2988485.50
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN,1828203.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727,251932.50
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822,106778.30
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251,607166.30
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251,209471.80
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081,675542.30

### Rolling liquidity

In [33]:
df["avg_value_20d"] = (
    df.groupby("symbol")["traded_value"]
      .rolling(20)
      .mean()
      .reset_index(level=0, drop=True)
)
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d
5972,20MICRONS,EQ,36.00,36.30,34.60,35.20,35.00,36.50,73518,2592129.15,610,INE144J01027,2016-01-01,NaN,NaN,NaN,NaN,2587833.60,NaN
41898,20MICRONS,EQ,35.55,37.50,34.75,35.90,35.95,35.20,258669,9428181.10,823,INE144J01027,2016-01-04,0.019886,NaN,NaN,NaN,9286217.10,NaN
56863,20MICRONS,EQ,36.45,36.70,35.40,35.55,35.50,35.90,74075,2653403.85,292,INE144J01027,2016-01-05,-0.009749,NaN,NaN,NaN,2633366.25,NaN
65880,20MICRONS,EQ,35.95,36.50,35.70,35.75,35.75,35.55,83594,3004382.60,307,INE144J01027,2016-01-06,0.005626,NaN,NaN,NaN,2988485.50,NaN
76398,20MICRONS,EQ,35.90,35.90,33.05,34.10,34.25,35.75,53613,1856282.15,354,INE144J01027,2016-01-07,-0.046154,NaN,NaN,NaN,1828203.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882361,ZYLOG,EQ,3.75,3.85,3.70,3.75,3.70,3.75,67182,252480.80,141,INE225I01026,2018-03-12,0.000000,0.013514,-0.038462,0.036727,251932.50,516479.575
895936,ZYLOG,EQ,3.70,3.75,3.70,3.70,3.70,3.75,28859,107022.65,74,INE225I01026,2018-03-13,-0.013333,-0.026316,-0.051282,0.036822,106778.30,498582.485
905051,ZYLOG,EQ,3.75,3.80,3.30,3.70,3.70,3.70,164099,593833.90,130,INE225I01026,2018-03-14,0.000000,-0.026316,-0.075000,0.036251,607166.30,510020.200
915515,ZYLOG,EQ,3.70,3.75,3.65,3.70,3.65,3.70,56614,209411.05,84,INE225I01026,2018-03-15,0.000000,-0.026316,-0.075000,0.036251,209471.80,503989.190
928993,ZYLOG,EQ,3.65,3.80,3.65,3.70,3.70,3.70,182579,681707.50,131,INE225I01026,2018-03-16,0.000000,-0.013333,0.000000,0.032081,675542.30,512279.965

## Applying Liquidity Filters

In [34]:
LIQUIDITY_THRESHOLD = 5e7

(₹5 crore average daily traded value)

### Filter dataset: clean tradable universe

In [35]:
df = df[df["avg_value_20d"] > LIQUIDITY_THRESHOLD]
df = df[df["close"] > 20]

### Data after Liquidity Filters

In [36]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d
2169246,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,11794,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07
2181909,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,5353,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07
2194689,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,4367,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07
2207322,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,5562,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07
2242200,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,2486,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4220159,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,3777,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07
4222579,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,5789,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07
4224997,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,8030,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07
4227414,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,10608,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07
4229837,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,11663,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07

## Relative Strength vs Index

Load index features

In [37]:
path = Path("../data/features/index")

files = sorted(path.glob("index_features_*.parquet"))

index_df = pd.concat(
    [pd.read_parquet(f) for f in files],
    ignore_index=True
)

index_df

,index_name,open_index_value,high_index_value,low_index_value,closing_index_value,points_change,change(%),volume,turnover_(rs._cr.),p/e,p/b,div_yield,trade_date,return_1d,return_5d,return_20d,volatility_20d,drawdown,volume_change,year
0,NIFTY 50,7938.45,7972.55,7909.80,7963.20,16.85,0.21,64843836,2613.91,21.53,3.19,1.45,2016-01-01,NaN,NaN,NaN,NaN,0.000000,NaN,2016
1,NIFTY 50,7924.55,7937.55,7781.10,7791.30,-171.90,-2.16,138864905,5897.08,21.07,3.13,1.48,2016-01-04,-0.021587,NaN,NaN,NaN,-0.021587,NaN,2016
2,NIFTY 50,7828.40,7831.20,7763.25,7784.65,-6.65,-0.09,149672973,5948.51,21.05,3.12,1.49,2016-01-05,-0.000854,NaN,NaN,NaN,-0.022422,NaN,2016
3,NIFTY 50,7788.05,7800.95,7721.20,7741.00,-43.65,-0.56,151715828,6722.17,20.93,3.10,1.49,2016-01-06,-0.005607,NaN,NaN,NaN,-0.027903,NaN,2016
4,NIFTY 50,7673.35,7674.95,7556.60,7568.30,-172.70,-2.23,194732861,7803.21,20.47,3.04,1.53,2016-01-07,-0.022310,NaN,NaN,NaN,-0.049591,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,NIFTY 50,25641.80,25641.80,25327.60,25424.65,-288.35,-1.12,439068188,36735.38,22.25,3.46,1.23,2026-02-24,-0.011214,-0.011691,0.003232,0.010048,-0.034332,0.160217,2026
2515,NIFTY 50,25512.60,25652.60,25428.20,25482.50,57.85,0.23,414215742,31084.17,22.30,3.46,1.22,2026-02-25,0.002275,-0.013046,0.002502,0.010038,-0.032134,0.033453,2026
2516,NIFTY 50,25556.30,25572.95,25400.95,25496.55,14.05,0.06,405219244,33155.50,22.31,3.47,1.22,2026-02-26,0.000551,0.001658,0.006947,0.009993,-0.031601,0.214472,2026
2517,NIFTY 50,25459.85,25476.40,25141.30,25178.65,-317.90,-1.25,438924282,38634.68,22.03,3.42,1.24,2026-02-27,-0.012468,-0.015353,0.014227,0.009354,-0.043675,0.418751,2026
2518,NIFTY 50,24659.25,24989.35,24603.50,24865.70,-312.95,-1.24,519228821,41306.37,21.76,3.38,1.25,2026-03-02,-0.012429,-0.032952,-0.008877,0.009494,-0.055561,0.300882,2026

Merging equity & index features

In [38]:
df = df.merge(
    index_df[["trade_date","return_1d"]],
    on="trade_date",
    suffixes=("","_index")
)

Merged Data

In [39]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,totaltrades,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,11794,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.000707
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,5353,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.006115
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,4367,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.002379
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,5562,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.006376
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,2486,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.009533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,3777,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,5789,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,8030,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,10608,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,-0.012468
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,11663,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.012429

### Compute relative strength

In [40]:
df["relative_strength"] = df["return_1d"] - df["return_1d_index"]
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,isin,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,INE144J01027,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.000707,0.014499
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,INE144J01027,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.006115,-0.031079
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,INE144J01027,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.002379,-0.005305
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,INE144J01027,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.006376,-0.072407
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,INE144J01027,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.009533,-0.002463
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,INE768C01028,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-0.007598
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,INE768C01028,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-0.015559
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,INE768C01028,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-0.023030
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,INE768C01028,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,-0.012468,0.012598
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,INE768C01028,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.012429,-0.003029

## Cross-Sectional Ranking

daily ranking across stocks

In [41]:
df["rank_momentum"] = (
    df.groupby("trade_date")["return_20d"]
      .rank(ascending=False)
)

In [42]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,trade_date,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,2021-05-25,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.000707,0.014499,3.0
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,2021-05-26,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.006115,-0.031079,3.0
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,2021-05-27,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.002379,-0.005305,4.0
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,2021-05-28,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.006376,-0.072407,8.0
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,2021-05-31,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.009533,-0.002463,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,2026-02-24,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-0.007598,874.0
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,2026-02-25,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-0.015559,930.0
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,2026-02-26,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-0.023030,1010.0
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,2026-02-27,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,-0.012468,0.012598,1013.0
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,2026-03-02,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.012429,-0.003029,984.0

return_20d = (Current Price - Price 20 days ago) / Price 20 days ago
</br>
| Symbol   | Price Today | Price 20d Ago | return_20d |
| -------- | ----------- | ------------- | ---------- |
| RELIANCE | 2600        | 2400          | 8.33%      |
| TCS      | 3800        | 3700          | 2.70%      |
| INFY     | 1600        | 1500          | 6.67%      |

</br>

| symbol   | return_20d | rank_momentum |
| -------- | ---------- | ------------- |
| RELIANCE | 8.33       | 1             |
| INFY     | 6.67       | 2             |
| TCS      | 2.70       | 3             |

Normalize ranking

In [43]:
df["rank_pct"] = (
    df.groupby("trade_date")["return_20d"]
      .rank(pct=True)
)

In [44]:
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,return_1d,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum,rank_pct
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,0.015206,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.000707,0.014499,3.0,0.997187
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,-0.024964,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.006115,-0.031079,3.0,0.997211
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,-0.002926,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.002379,-0.005305,4.0,0.995868
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,-0.066031,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.006376,-0.072407,8.0,0.990437
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,0.007070,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.009533,-0.002463,9.0,0.989218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,-0.018812,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-0.007598,874.0,0.210669
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,-0.013283,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-0.015559,930.0,0.153145
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,-0.022479,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-0.023030,1010.0,0.076853
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,0.000130,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,-0.012468,0.012598,1013.0,0.073260
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,-0.015459,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.012429,-0.003029,984.0,0.099817

Important detail: .rank(pct=True) ranks in ascending order by default.
</br>
| symbol   | return_20d |
| -------- | ---------- |
| TCS      | 2.70       |
| INFY     | 6.67       |
| RELIANCE | 8.33       |

</br>

| symbol   | return_20d | rank |
| -------- | ---------- | ---- |
| TCS      | 2.70       | 1    |
| INFY     | 6.67       | 2    |
| RELIANCE | 8.33       | 3    |


rank_pct = (rank) / (total stocks)

</br>

| symbol   | rank | rank_pct       |
| -------- | ---- | -------------- |
| TCS      | 1    | 1/3 = **0.33** |
| INFY     | 2    | 2/3 = **0.67** |
| RELIANCE | 3    | 3/3 = **1.00** |


</br>

| symbol   | return_20d | rank_momentum | rank_pct |
| -------- | ---------- | ------------- | -------- |
| RELIANCE | 8.33       | 1             | **1.00** |
| INFY     | 6.67       | 2             | **0.67** |
| TCS      | 2.70       | 3             | **0.33** |

</br>

rank_pct tells how strong a stock’s momentum is relative to all other stocks on that day.
</br>
<ul>
<li>1.0 → best performer</li>

<li>0.5 → average</li>

<li>0.1 → poor performer</li>
</ul>

## Save Features (Partitioned Parquet)

In [45]:
df["year"] = df["trade_date"].dt.year
df

,symbol,series,open,high,low,close,last,prevclose,tottrdqty,tottrdval,...,return_5d,return_20d,volatility_20d,traded_value,avg_value_20d,return_1d_index,relative_strength,rank_momentum,rank_pct,year
0,20MICRONS,EQ,70.50,74.90,68.40,70.10,70.80,69.05,1439386,1.029330e+08,...,0.228747,0.941828,0.070425,1.009010e+08,5.423314e+07,0.000707,0.014499,3.0,0.997187,2021
1,20MICRONS,EQ,70.95,73.00,67.50,68.35,68.70,70.10,564132,3.978479e+07,...,0.251832,0.839838,0.071726,3.855842e+07,5.602199e+07,0.006115,-0.031079,3.0,0.997211,2021
2,20MICRONS,EQ,68.90,69.75,66.00,68.15,67.60,68.35,547676,3.718503e+07,...,0.043645,0.812500,0.072036,3.732412e+07,5.778274e+07,0.002379,-0.005305,4.0,0.995868,2021
3,20MICRONS,EQ,69.00,69.50,62.25,63.65,64.45,68.15,682674,4.452229e+07,...,0.013535,0.644703,0.075334,4.345220e+07,5.970589e+07,0.006376,-0.072407,8.0,0.990437,2021
4,20MICRONS,EQ,64.65,66.30,63.00,64.10,64.40,63.65,257439,1.664345e+07,...,-0.071687,0.678010,0.074898,1.650184e+07,5.998341e+07,0.009533,-0.002463,9.0,0.989218,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595640,ZYDUSWELL,EQ,406.65,406.65,395.00,399.00,398.75,406.65,69035,2.756971e+07,...,-0.016272,-0.057517,0.023363,2.754496e+07,7.473001e+07,-0.011214,-0.007598,874.0,0.210669,2026
1595641,ZYDUSWELL,EQ,401.80,402.45,390.00,393.70,393.45,399.00,87399,3.455154e+07,...,-0.020037,-0.086967,0.022920,3.440899e+07,7.361551e+07,0.002275,-0.015559,930.0,0.153145,2026
1595642,ZYDUSWELL,EQ,393.95,396.50,382.35,384.85,385.00,393.70,162847,6.309842e+07,...,-0.038596,-0.141535,0.020759,6.267167e+07,7.311029e+07,0.000551,-0.023030,1010.0,0.076853,2026
1595643,ZYDUSWELL,EQ,386.70,389.10,378.10,384.90,387.85,384.85,257971,9.879698e+07,...,-0.035942,-0.125625,0.020665,9.929304e+07,7.706981e+07,-0.012468,0.012598,1013.0,0.073260,2026
1595644,ZYDUSWELL,EQ,367.60,384.15,367.55,378.95,380.00,384.90,172585,6.548232e+07,...,-0.068118,-0.129051,0.020734,6.540109e+07,7.802515e+07,-0.012429,-0.003029,984.0,0.099817,2026

In [46]:
import sys
from pathlib import Path

# Add project root directory to sys.path
sys.path.append(str(Path().resolve().parents[0]))

# importing get_logger function from scripts.logger
from scripts.logger import get_logger

logger = get_logger(__name__)

output_path = Path("../data/features/equity")

# Create equity if not exists
if not output_path.exists():
    output_path.mkdir(parents=True, exist_ok=True)
    logger.info(f"Created directory: {output_path}")
else:
    logger.info(f"Directory already exisits:{output_path}")

years = df["year"].unique()

for year in years:
    try:
    
        df_year = df[df["year"] == year]
        
        file_path = output_path / f"equity_features_{year}.parquet"
        
        # Check if parquet already exists
        if file_path.exists():
            logger.info(f"File already exists for year {year}: {file_path}")
        else:
            df_year.to_parquet(file_path, index=False)
            logger.info(f"Parquet file created for year {year}: {file_path}")

    except Exception as e:
        logger.error(f"Error while creating parquet for year {year}: {e}")